### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by ArtGangsta** [VSadov/NonBlocking#4]
Do you have any recommendations on how to generate those charts because I would like to know how it compares against a regular dictionary.

**Comment by VSadov** [comment]
I just used office/excel. There must be better ways, but for a handful of charts excel was good enough.

I'd expect that regular dictionary is faster, especially on small dictionary sizes and sequential accesses. Not sure by how much though. Might vary by the kinds of keys/values, size of data, pattern of access.
