### ISSUE TITLE
Many compile error

### ISSUE THREAD

**Issue by MBurtsev** [VSadov/NonBlocking#5]
Hello, after download I try compile code:

![GitHub Logo](https://i.imgur.com/yR8bgNt.png)

![GitHub Logo](https://i.imgur.com/4jM9tmi.png)

If you post code, it’s good to be able to compile.

**Comment by nerai** [comment]
I had no trouble with the current master.

**Comment by MBurtsev** [comment]
I had a problem with nuget sorry.
